version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: journal_db
    environment:
      POSTGRES_USER: journaladmin
      POSTGRES_PASSWORD: 3RmXJ6uvRo3e
      POSTGRES_DB: journal
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
